// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 14.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************
class Assets {
  static const String package = 'banban_demo';

  static const String assets_images_bg_welcome_entry_1_png = 'assets/images/bg_welcome_entry_1.png';
  static const String banban_demo$assets_images_bg_welcome_entry_1_png = 'packages/banban_demo/assets/images/bg_welcome_entry_1.png';

  static const String assets_images_ic_gender_inset_female_webp = 'assets/images/ic_gender_inset_female.webp';
  static const String banban_demo$assets_images_ic_gender_inset_female_webp = 'packages/banban_demo/assets/images/ic_gender_inset_female.webp';

  static const String assets_images_ic_gender_inset_female_checked_webp = 'assets/images/ic_gender_inset_female_checked.webp';
  static const String banban_demo$assets_images_ic_gender_inset_female_checked_webp = 'packages/banban_demo/assets/images/ic_gender_inset_female_checked.webp';

  static const String assets_images_ic_gender_inset_male_webp = 'assets/images/ic_gender_inset_male.webp';
  static const String banban_demo$assets_images_ic_gender_inset_male_webp = 'packages/banban_demo/assets/images/ic_gender_inset_male.webp';

  static const String assets_images_ic_gender_inset_male_checked_webp = 'assets/images/ic_gender_inset_male_checked.webp';
  static const String banban_demo$assets_images_ic_gender_inset_male_checked_webp = 'packages/banban_demo/assets/images/ic_gender_inset_male_checked.webp';

  static const String assets_images_ic_login_avatar_svg = 'assets/images/ic_login_avatar.svg';
  static const String banban_demo$assets_images_ic_login_avatar_svg = 'packages/banban_demo/assets/images/ic_login_avatar.svg';

  static const String assets_images_tab_discovery_svg = 'assets/images/tab_discovery.svg';
  static const String banban_demo$assets_images_tab_discovery_svg = 'packages/banban_demo/assets/images/tab_discovery.svg';

  static const String assets_images_tab_discovery_webp = 'assets/images/tab_discovery.webp';
  static const String banban_demo$assets_images_tab_discovery_webp = 'packages/banban_demo/assets/images/tab_discovery.webp';

  static const String assets_images_tab_home_svg = 'assets/images/tab_home.svg';
  static const String banban_demo$assets_images_tab_home_svg = 'packages/banban_demo/assets/images/tab_home.svg';

  static const String assets_images_tab_home_webp = 'assets/images/tab_home.webp';
  static const String banban_demo$assets_images_tab_home_webp = 'packages/banban_demo/assets/images/tab_home.webp';

  static const String assets_images_tab_me_svg = 'assets/images/tab_me.svg';
  static const String banban_demo$assets_images_tab_me_svg = 'packages/banban_demo/assets/images/tab_me.svg';

  static const String assets_images_tab_me_webp = 'assets/images/tab_me.webp';
  static const String banban_demo$assets_images_tab_me_webp = 'packages/banban_demo/assets/images/tab_me.webp';

  static const String assets_images_tab_msg_svg = 'assets/images/tab_msg.svg';
  static const String banban_demo$assets_images_tab_msg_svg = 'packages/banban_demo/assets/images/tab_msg.svg';

  static const String assets_images_tab_msg_webp = 'assets/images/tab_msg.webp';
  static const String banban_demo$assets_images_tab_msg_webp = 'packages/banban_demo/assets/images/tab_msg.webp';
}
